const assert=require('node:assert/strict');
const {test}=require('node:test');
const layout=require('../../static/js/reports_layout.js');
const fixture=()=>[{id:'section',type:'section',props:{style:{padding:2}},children:[{id:'text',type:'text',props:{text:'Original'}}]},{id:'other',type:'section',props:{},children:[]}];
test('duplicate subtree with independent content and fresh ids',()=>{const nodes=fixture();let id=0;const copy=layout.duplicate(nodes,'section',()=>String(++id));assert.equal(copy.children[0].id,'2');copy.children[0].props.text='Copy';assert.equal(nodes[0].children[0].props.text,'Original');layout.validate(nodes);});
test('move siblings, reparent and delete subtree',()=>{const nodes=fixture();assert.equal(layout.move(nodes,'text',1),false);layout.reparent(nodes,'text','other');assert.equal(nodes[0].children.length,0);assert.equal(nodes[1].children[0].id,'text');layout.move(nodes,'other',-1);assert.equal(nodes[0].id,'other');layout.remove(nodes,'other');assert.equal(layout.locate(nodes,'text'),undefined);});
test('reject cycles and unknown destinations without mutation',()=>{const nodes=fixture(),before=JSON.stringify(nodes);assert.throws(()=>layout.reparent(nodes,'section','section'));assert.throws(()=>layout.reparent(nodes,'section','text'));assert.throws(()=>layout.reparent(nodes,'text','unknown'));assert.equal(JSON.stringify(nodes),before);});
test('rollback duplication on node limit',()=>{const nodes=Array.from({length:200},(_,i)=>({id:String(i),type:'text',props:{text:''}}));assert.throws(()=>layout.duplicate(nodes,'0',()=> 'copy'));assert.equal(nodes.length,200);});
test('rollback reparenting on depth limit',()=>{const nodes=fixture();let parent=nodes[1];for(let i=0;i<7;i++){const child={id:'level'+i,type:'section',props:{},children:[]};parent.children.push(child);parent=child;}const before=JSON.stringify(nodes);assert.throws(()=>layout.reparent(nodes,'section',parent.id));assert.equal(JSON.stringify(nodes),before);});

test('reject reparenting forced break into columns and rollback',()=>{const nodes=fixture();nodes[1].props.columns=2;nodes[0].children[0].props.pagination={break_before:true};const before=JSON.stringify(nodes);assert.throws(()=>layout.reparent(nodes,'text','other'));assert.equal(JSON.stringify(nodes),before);nodes[0].children[0].props.pagination={keep_together:true};assert.equal(layout.reparent(nodes,'text','other'),true);});
test('insert block with fresh descendant ids and independent properties',()=>{const nodes=fixture(),snapshot=JSON.parse(JSON.stringify(nodes[0]));let id=0;const copy=layout.insert(nodes,snapshot,'other',()=> 'fresh'+(++id));copy.children[0].props.text='Inserted';assert.equal(snapshot.children[0].props.text,'Original');assert.equal(copy.children[0].id,'fresh2');assert.equal(nodes[1].children[0],copy);});
test('rollback block insertion into forbidden column destination',()=>{const nodes=fixture();nodes[1].props.columns=2;const before=JSON.stringify(nodes);assert.throws(()=>layout.insert(nodes,{id:'x',type:'page_break',props:{}},'other',()=> 'new'));assert.equal(JSON.stringify(nodes),before);});
