"""skill23 fase4 pedido compra item pedido compra

Revision ID: 0451604f9aad
Revises: 39c5bada7f65
Create Date: 2026-08-26 14:26:37.312509

CORREÇÃO MANUAL (mesma classe de achado documentada em f44a00fd711f e
39c5bada7f65): 5 FKs em create_table() vieram com nome de tabela sem
prefixo tri-nível (skill 02) - corrigidas à mão. Além disso, 3
constraints em create_foreign_key() dentro de batch_alter_table()
vieram sem nome (None) - mesmo bug "Constraint must have a name" já
corrigido no hotfix de 7faf3d2c92ca -, nomeadas aqui e refletidas no
downgrade().
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0451604f9aad'
down_revision = '39c5bada7f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tesseract_estoque_pedido_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('transportadora_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_pedido', sa.Date(), nullable=False),
    sa.Column('data_previsao_entrega', sa.Date(), nullable=True),
    sa.Column('condicao_pagamento', sa.String(length=100), nullable=True),
    sa.Column('valor_frete', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['tesseract_estoque_fornecedor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transportadora_id'], ['tesseract_estoque_transportadora.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    with op.batch_alter_table('tesseract_estoque_pedido_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_compra_fornecedor_id'), ['fornecedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_compra_transportadora_id'), ['transportadora_id'], unique=False)

    op.create_table('tesseract_estoque_item_pedido_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_compra_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('material_unidade_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('fator_conversao_aplicado', sa.Float(), nullable=True),
    sa.Column('quantidade_convertida_base', sa.Float(), nullable=True),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['tesseract_estoque_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_unidade_id'], ['tesseract_estoque_material_unidade.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pedido_compra_id'], ['tesseract_estoque_pedido_compra.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tesseract_estoque_item_pedido_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_pedido_compra_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_pedido_compra_material_unidade_id'), ['material_unidade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_pedido_compra_pedido_compra_id'), ['pedido_compra_id'], unique=False)

    with op.batch_alter_table('tesseract_estoque_movimentacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fornecedor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pedido_compra_item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unidade_original', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('quantidade_original', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fator_conversao_aplicado', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_movimentacao_fornecedor_id'), ['fornecedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacao_pedido_compra_item_id'), ['pedido_compra_item_id'], unique=False)
        batch_op.create_foreign_key('fk_movimentacao_fornecedor_id', 'tesseract_estoque_fornecedor', ['fornecedor_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key('fk_movimentacao_pedido_compra_item_id', 'tesseract_estoque_item_pedido_compra', ['pedido_compra_item_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('tesseract_estoque_saldo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_preco_compra', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ultimo_fornecedor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_ultima_compra', sa.Date(), nullable=True))
        batch_op.create_foreign_key('fk_saldo_ultimo_fornecedor_id', 'tesseract_estoque_fornecedor', ['ultimo_fornecedor_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tesseract_estoque_saldo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_saldo_ultimo_fornecedor_id', type_='foreignkey')
        batch_op.drop_column('data_ultima_compra')
        batch_op.drop_column('ultimo_fornecedor_id')
        batch_op.drop_column('ultimo_preco_compra')

    with op.batch_alter_table('tesseract_estoque_movimentacao', schema=None) as batch_op:
        batch_op.drop_constraint('fk_movimentacao_pedido_compra_item_id', type_='foreignkey')
        batch_op.drop_constraint('fk_movimentacao_fornecedor_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_movimentacao_pedido_compra_item_id'))
        batch_op.drop_index(batch_op.f('ix_movimentacao_fornecedor_id'))
        batch_op.drop_column('fator_conversao_aplicado')
        batch_op.drop_column('quantidade_original')
        batch_op.drop_column('unidade_original')
        batch_op.drop_column('pedido_compra_item_id')
        batch_op.drop_column('fornecedor_id')

    with op.batch_alter_table('tesseract_estoque_item_pedido_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_pedido_compra_pedido_compra_id'))
        batch_op.drop_index(batch_op.f('ix_item_pedido_compra_material_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_item_pedido_compra_material_id'))

    op.drop_table('tesseract_estoque_item_pedido_compra')
    with op.batch_alter_table('tesseract_estoque_pedido_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_compra_transportadora_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_compra_fornecedor_id'))

    op.drop_table('tesseract_estoque_pedido_compra')
    # ### end Alembic commands ###
