"""skill23 fase3 fornecedor transportadora endereco

Revision ID: 39c5bada7f65
Revises: f44a00fd711f
Create Date: 2026-08-26 12:15:25.993477

CORREÇÃO MANUAL (mesmo achado documentado em f44a00fd711f): o
autogenerate capturou as 4 FKs (fornecedor_endereco/
transportadora_endereco -> endereco/fornecedor/transportadora) pelo
nome curto do model em vez do nome de tabela prefixado (skill 02).
Corrigido à mão abaixo.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c5bada7f65'
down_revision = 'f44a00fd711f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tesseract_estoque_endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('pais', sa.String(length=60), nullable=False),
    sa.Column('cep', sa.String(length=15), nullable=True),
    sa.Column('ponto_referencia', sa.String(length=200), nullable=True),
    sa.Column('descricao', sa.String(length=150), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tesseract_estoque_fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=True),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('contato_nome', sa.String(length=150), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('condicao_pagamento_padrao', sa.String(length=100), nullable=True),
    sa.Column('prazo_entrega_padrao_dias', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tesseract_estoque_transportadora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('contato_nome', sa.String(length=150), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('tipo_frete', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tesseract_estoque_fornecedor_endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('endereco_id', sa.Integer(), nullable=False),
    sa.Column('tipo_endereco', sa.String(length=20), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['endereco_id'], ['tesseract_estoque_endereco.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['tesseract_estoque_fornecedor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tesseract_estoque_fornecedor_endereco', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fornecedor_endereco_endereco_id'), ['endereco_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fornecedor_endereco_fornecedor_id'), ['fornecedor_id'], unique=False)
        batch_op.create_index('uq_fornecedor_endereco_principal', ['fornecedor_id'], unique=True, sqlite_where=sa.text('principal = 1 AND is_deleted = 0'))

    op.create_table('tesseract_estoque_transportadora_endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transportadora_id', sa.Integer(), nullable=False),
    sa.Column('endereco_id', sa.Integer(), nullable=False),
    sa.Column('tipo_endereco', sa.String(length=20), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['endereco_id'], ['tesseract_estoque_endereco.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transportadora_id'], ['tesseract_estoque_transportadora.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tesseract_estoque_transportadora_endereco', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transportadora_endereco_endereco_id'), ['endereco_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transportadora_endereco_transportadora_id'), ['transportadora_id'], unique=False)
        batch_op.create_index('uq_transportadora_endereco_principal', ['transportadora_id'], unique=True, sqlite_where=sa.text('principal = 1 AND is_deleted = 0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tesseract_estoque_transportadora_endereco', schema=None) as batch_op:
        batch_op.drop_index('uq_transportadora_endereco_principal', sqlite_where=sa.text('principal = 1 AND is_deleted = 0'))
        batch_op.drop_index(batch_op.f('ix_transportadora_endereco_transportadora_id'))
        batch_op.drop_index(batch_op.f('ix_transportadora_endereco_endereco_id'))

    op.drop_table('tesseract_estoque_transportadora_endereco')
    with op.batch_alter_table('tesseract_estoque_fornecedor_endereco', schema=None) as batch_op:
        batch_op.drop_index('uq_fornecedor_endereco_principal', sqlite_where=sa.text('principal = 1 AND is_deleted = 0'))
        batch_op.drop_index(batch_op.f('ix_fornecedor_endereco_fornecedor_id'))
        batch_op.drop_index(batch_op.f('ix_fornecedor_endereco_endereco_id'))

    op.drop_table('tesseract_estoque_fornecedor_endereco')
    op.drop_table('tesseract_estoque_transportadora')
    op.drop_table('tesseract_estoque_fornecedor')
    op.drop_table('tesseract_estoque_endereco')
    # ### end Alembic commands ###
