"""skill24 fase61 processo cotacao cotacao item cotacao

Revision ID: 6ddc874d16e7
Revises: 0451604f9aad
Create Date: 2026-08-26 18:06:03.055946

CORREÇÃO MANUAL (5ª ocorrência do mesmo achado sistemático — ver
f44a00fd711f, 39c5bada7f65, 0451604f9aad, hotfix de 7faf3d2c92ca): 5
FKs em create_table() vieram com nome de tabela sem prefixo tri-nível
(skill 02) - corrigidas à mão.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ddc874d16e7'
down_revision = '0451604f9aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tesseract_estoque_processo_cotacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_abertura', sa.Date(), nullable=False),
    sa.Column('data_limite_resposta', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('tesseract_estoque_cotacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processo_cotacao_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('condicao_pagamento', sa.String(length=100), nullable=True),
    sa.Column('prazo_entrega_dias', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['tesseract_estoque_fornecedor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['processo_cotacao_id'], ['tesseract_estoque_processo_cotacao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    with op.batch_alter_table('tesseract_estoque_cotacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cotacao_fornecedor_id'), ['fornecedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cotacao_processo_cotacao_id'), ['processo_cotacao_id'], unique=False)
        batch_op.create_index('uq_cotacao_processo_fornecedor', ['processo_cotacao_id', 'fornecedor_id'], unique=True, sqlite_where=sa.text('is_deleted = 0'))

    op.create_table('tesseract_estoque_item_cotacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotacao_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('material_unidade_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('fator_conversao_aplicado', sa.Float(), nullable=True),
    sa.Column('quantidade_convertida_base', sa.Float(), nullable=True),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('selecionado_como_vencedor', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cotacao_id'], ['tesseract_estoque_cotacao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['tesseract_estoque_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_unidade_id'], ['tesseract_estoque_material_unidade.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tesseract_estoque_item_cotacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_cotacao_cotacao_id'), ['cotacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_cotacao_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_cotacao_material_unidade_id'), ['material_unidade_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tesseract_estoque_item_cotacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_cotacao_material_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_item_cotacao_material_id'))
        batch_op.drop_index(batch_op.f('ix_item_cotacao_cotacao_id'))

    op.drop_table('tesseract_estoque_item_cotacao')
    with op.batch_alter_table('tesseract_estoque_cotacao', schema=None) as batch_op:
        batch_op.drop_index('uq_cotacao_processo_fornecedor', sqlite_where=sa.text('is_deleted = 0'))
        batch_op.drop_index(batch_op.f('ix_cotacao_processo_cotacao_id'))
        batch_op.drop_index(batch_op.f('ix_cotacao_fornecedor_id'))

    op.drop_table('tesseract_estoque_cotacao')
    op.drop_table('tesseract_estoque_processo_cotacao')
    # ### end Alembic commands ###
