"""Inicio ajustes estoque, categoria

Revision ID: 7faf3d2c92ca
Revises: da6e6b8c5522
Create Date: 2026-08-25 10:25:10.781820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7faf3d2c92ca'
down_revision = 'da6e6b8c5522'
branch_labels = None
depends_on = None

_TABLE = 'tesseract_estoque_categoria'


def _columns():
    inspector = sa.inspect(op.get_bind())
    if _TABLE not in inspector.get_table_names():
        return None
    return {column['name'] for column in inspector.get_columns(_TABLE)}


def upgrade():
    columns = _columns()
    if columns is None:
        return
    if 'nome' not in columns:
        # Um banco iniciado com db.create_all() ja tem o esquema atual.
        # Tambem cobre uma tentativa anterior de upgrade parcialmente aplicada.
        if {'descricao', 'codigo'} <= columns:
            return
        raise RuntimeError('Categoria sem nome e sem descricao/codigo: confira o esquema antes de migrar')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tesseract_estoque_categoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('codigo', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint('uq_categoria_codigo', ['codigo'])
        batch_op.create_unique_constraint('uq_categoria_descricao', ['descricao'])
        batch_op.drop_column('nome')

    # ### end Alembic commands ###


def downgrade():
    columns = _columns()
    if columns is None or 'nome' in columns:
        return
    from migrations.schema_compat import drop_columns_with_references
    with op.batch_alter_table(_TABLE) as batch:
        batch.add_column(sa.Column('nome', sa.String(length=100), nullable=True))
    op.get_bind().execute(sa.text('UPDATE tesseract_estoque_categoria SET nome = descricao'))
    drop_columns_with_references(op, _TABLE, ['codigo', 'descricao'])
    with op.batch_alter_table(_TABLE) as batch:
        batch.alter_column('nome', existing_type=sa.String(length=100), nullable=False)
