"""Inicio ajustes estoque, categoria

Revision ID: 7faf3d2c92ca
Revises: da6e6b8c5522
Create Date: 2026-08-25 10:25:10.781820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7faf3d2c92ca'
down_revision = 'da6e6b8c5522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tesseract_estoque_categoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('codigo', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['codigo'])
        batch_op.create_unique_constraint(None, ['descricao'])
        batch_op.drop_column('nome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tesseract_estoque_categoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('codigo')
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###
