"""ajustando config levedura por tipo de harmazenamento

Revision ID: aa7341e86ae3
Revises: f6f47fbb19af
Create Date: 2026-08-20 12:55:14.742816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7341e86ae3'
down_revision = 'f6f47fbb19af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tesseract_brewstation_yeastbank_bank_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_type', sa.String(length=40), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tesseract_brewstation_yeastbank_bank_config', schema=None) as batch_op:
        batch_op.drop_column('storage_type')

    # ### end Alembic commands ###
