"""skill23 fase1 fase2 taxonomia e fracionamento estoque

Revision ID: f44a00fd711f
Revises: 7faf3d2c92ca
Create Date: 2026-08-26 01:54:32.930395

CORREÇÃO MANUAL (skill 23, achado ao validar upgrade/downgrade em
clone limpo): o autogenerate do Alembic, quando roda sob `flask db
migrate` (contexto em que `create_all_pending_tables()` deliberadamente
não recria o metadata prefixado - ver core/module_manager.py), capturou
o alvo da FK de MaterialUnidade.material_id pelo nome CURTO do model
("material.id", como declarado no código-fonte via
db.ForeignKey("material.id")) em vez do nome de tabela real já
prefixado ("tesseract_estoque_material.id", skill 02). Confirmado o bug
aplicando a migration original num banco limpo: `CREATE TABLE` saía com
`REFERENCES material (id)` - tabela que não existe, FK dangling.
Corrigido à mão abaixo. Vale a pena registrar como cuidado geral do
projeto: toda migration autogerada que envolva FK para uma tabela de
Addon/Feature (nome prefixado em runtime) deve ter o nome de tabela
alvo conferido manualmente antes de aceitar o arquivo gerado.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44a00fd711f'
down_revision = '7faf3d2c92ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tesseract_estoque_material_unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('fator_para_base', sa.Float(), nullable=False),
    sa.Column('is_unidade_base', sa.Boolean(), nullable=False),
    sa.Column('tipo_uso', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['tesseract_estoque_material.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tesseract_estoque_material_unidade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_unidade_material_id'), ['material_id'], unique=False)
        batch_op.create_index('uq_material_unidade_base_por_material', ['material_id'], unique=True, sqlite_where=sa.text('is_unidade_base = 1 AND is_deleted = 0'))

    with op.batch_alter_table('tesseract_estoque_categoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_produto_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_categoria_tipo_produto_id'), ['tipo_produto_id'], unique=False)
        batch_op.create_foreign_key('fk_categoria_tipo_produto_id', 'tesseract_estoque_tipo_produto', ['tipo_produto_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tesseract_estoque_categoria', schema=None) as batch_op:
        batch_op.drop_constraint('fk_categoria_tipo_produto_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_categoria_tipo_produto_id'))
        batch_op.drop_column('tipo_produto_id')

    with op.batch_alter_table('tesseract_estoque_material_unidade', schema=None) as batch_op:
        batch_op.drop_index('uq_material_unidade_base_por_material', sqlite_where=sa.text('is_unidade_base = 1 AND is_deleted = 0'))
        batch_op.drop_index(batch_op.f('ix_material_unidade_material_id'))

    op.drop_table('tesseract_estoque_material_unidade')
    # ### end Alembic commands ###
