"""Ajuste inclusao identification no item do banco de leveduras

Revision ID: f6f47fbb19af
Revises: b7e4d19a63c5
Create Date: 2026-08-20 10:39:56.785465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f47fbb19af'
down_revision = 'b7e4d19a63c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tesseract_brewstation_mashctrl_recipe_step', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tesseract_brewstation_mashctrl_recipe_step_recipe_id'))
        batch_op.create_index(batch_op.f('ix_recipe_step_recipe_id'), ['recipe_id'], unique=False)

    with op.batch_alter_table('tesseract_brewstation_yeastbank_bank_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identification', sa.String(length=255), nullable=True))

    with op.batch_alter_table('tesseract_brewstation_yeastbank_strain', schema=None) as batch_op:
        batch_op.alter_column('family',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('tesseract_designer_data_action', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('tesseract_model_field_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tesseract_model_field_definition_model_definition_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tesseract_model_field_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tesseract_model_field_definition_model_definition_id'), ['model_definition_id'], unique=False)

    with op.batch_alter_table('tesseract_designer_data_action', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('tesseract_brewstation_yeastbank_strain', schema=None) as batch_op:
        batch_op.alter_column('family',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('tesseract_brewstation_yeastbank_bank_item', schema=None) as batch_op:
        batch_op.drop_column('identification')

    with op.batch_alter_table('tesseract_brewstation_mashctrl_recipe_step', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_step_recipe_id'))
        batch_op.create_index(batch_op.f('ix_tesseract_brewstation_mashctrl_recipe_step_recipe_id'), ['recipe_id'], unique=False)

    # ### end Alembic commands ###
