"""skill24 fase63 item cotacao pedido compra item id

Revision ID: fd143ed5695c
Revises: 6ddc874d16e7
Create Date: 2026-08-26 19:53:43.401715

CORREÇÃO MANUAL (mesma classe de achado sistemático — ver
f44a00fd711f, 39c5bada7f65, 0451604f9aad, 6ddc874d16e7, hotfix de
7faf3d2c92ca): create_foreign_key() dentro de batch_alter_table()
veio sem nome (None) — "Constraint must have a name" no SQLite.
Nomeada e refletida no downgrade().
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd143ed5695c'
down_revision = '6ddc874d16e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tesseract_estoque_item_cotacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pedido_compra_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_item_cotacao_pedido_compra_item_id', 'tesseract_estoque_item_pedido_compra', ['pedido_compra_item_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tesseract_estoque_item_cotacao', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_cotacao_pedido_compra_item_id', type_='foreignkey')
        batch_op.drop_column('pedido_compra_item_id')

    # ### end Alembic commands ###
